#!/usr/bin/env bash
# Open (and, when explicitly told, merge) a PR for a completed generation task's
# branch. Deterministic — no LLM call here; this only reads structured state
# other tasks already produced (test results, review verdicts) and talks to gh.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$ROOT/.." && pwd)"
TASKS="$ROOT/tasks.json"

ACTION="${1:?usage: pr.sh <open|merge> <generation-task-id>}"
TASK_ID="${2:?usage: pr.sh <open|merge> <generation-task-id>}"

task=$(jq -c --arg id "$TASK_ID" '.tasks[] | select(.id==$id)' "$TASKS")
[ -n "$task" ] || { echo "unknown task id: $TASK_ID" >&2; exit 1; }

branch=$(jq -r '.branch' <<<"$task")
title=$(jq -r '.title' <<<"$task")
[ -n "$branch" ] && [ "$branch" != "null" ] || { echo "task $TASK_ID has no branch" >&2; exit 1; }

pr_body_file="$ROOT/outputs/$TASK_ID/pr-body.md"

build_body() {
  {
    echo "Automated migration branch for task \`$TASK_ID\`: $title"
    echo
    echo "Generated by \`migration/dispatch.sh\` per \`migration/PLAN.md\`."
    echo "Model used: $(jq -r '.model_used // .model' <<<"$task")"
    echo
    echo "## Test gate"
    echo
    echo '```'
    jq -r '.tests_status // "not run"' <<<"$task"
    echo '```'
    echo
    echo "## Review verdicts"
    echo
    # every review task whose depends_on includes this task id
    jq -r --arg id "$TASK_ID" '
      [ .tasks[] | select(.kind=="review" and (.depends_on | index($id)) != null) ] as $reviews
      | $reviews[] | "- \(.id) (\(.model)): see migration/logs/\(.id).log"
    ' "$TASKS"
  } > "$pr_body_file"
}

case "$ACTION" in
  open)
    build_body
    existing=$(gh pr list --repo "$(gh repo view --json nameWithOwner -q .nameWithOwner)" \
      --head "$branch" --json number -q '.[0].number' 2>/dev/null || true)
    if [ -n "$existing" ] && [ "$existing" != "null" ]; then
      echo "PR already open for $branch: #$existing"
      exit 0
    fi
    git -C "$REPO" push -u origin "$branch"
    gh pr create --repo "$(gh repo view --json nameWithOwner -q .nameWithOwner)" \
      --base main --head "$branch" \
      --title "feat(migration): $title ($TASK_ID)" \
      --body-file "$pr_body_file"
    ;;
  merge)
    # Hard gate: tests must have passed, and every dependent review task must
    # both be "done" AND end its log with an explicit VERDICT: PASS line.
    tests_status=$(jq -r '.tests_status // "not run"' <<<"$task")
    if [ "$tests_status" != "passed" ]; then
      echo "BLOCKED: tests_status is '$tests_status', not 'passed' — refusing to merge $branch" >&2
      exit 1
    fi

    review_ids=$(jq -r --arg id "$TASK_ID" '
      [ .tasks[] | select(.kind=="review" and (.depends_on | index($id)) != null) | .id ] | .[]
    ' "$TASKS")
    if [ -z "$review_ids" ]; then
      echo "BLOCKED: no review tasks found for $TASK_ID — refusing to merge $branch" >&2
      exit 1
    fi
    for rid in $review_ids; do
      rstatus=$(jq -r --arg id "$rid" '.tasks[] | select(.id==$id) | .status' "$TASKS")
      if [ "$rstatus" != "done" ]; then
        echo "BLOCKED: review $rid status is '$rstatus', not 'done' — refusing to merge $branch" >&2
        exit 1
      fi
      log="$ROOT/logs/$rid.log"
      if ! grep -q '^VERDICT: PASS$' "$log" 2>/dev/null; then
        echo "BLOCKED: review $rid did not emit VERDICT: PASS (see $log) — refusing to merge $branch" >&2
        exit 1
      fi
    done

    pr_number=$(gh pr list --repo "$(gh repo view --json nameWithOwner -q .nameWithOwner)" \
      --head "$branch" --json number -q '.[0].number')
    [ -n "$pr_number" ] && [ "$pr_number" != "null" ] || { echo "no open PR for $branch" >&2; exit 1; }

    gh pr merge "$pr_number" --repo "$(gh repo view --json nameWithOwner -q .nameWithOwner)" \
      --squash --delete-branch
    echo "merged PR #$pr_number ($branch -> main)"
    ;;
  *)
    echo "unknown action: $ACTION (expected open|merge)" >&2
    exit 1
    ;;
esac
